import { Source_Sans_3, Inter } from "next/font/google";
import '../scss/global.scss';
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import StyledComponentsRegistry from "@/lib/registry";

const sourceSansPro = Source_Sans_3({
  variable: "--font-source-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sourceSansPro.variable} ${inter.variable}`}>
        <StyledComponentsRegistry>
          <Header/>
          {children}
          <Footer/>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
